// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-08-01 16:45:50.194962 +0800 CST m=+4.050606701

package docs

import (
	"bytes"
	"encoding/json"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "This is a sample server Petstore server.",
        "title": "EVHarbor API",
        "termsOfService": "http://obs.casearth.cn/",
        "contact": {
            "name": "API Support",
            "url": "http://obs.casearth.cn/",
            "email": "helpdesk@cnic.cn"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0"
    },
    "host": "127.0.0.1:9000",
    "basePath": "/",
    "paths": {
        "/api/v1/buckets/": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过query参数“offset”和“limit”自定义获取存储桶列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bucket 存储桶"
                ],
                "summary": "获取存储桶列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "The initial index from which to return the results",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to return per page",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BucketListJSON"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "存储桶名称只能由字母、数字和“-”组成，且不能以“-”开头和结尾，长度3-64字符，符合DNS标准。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bucket 存储桶"
                ],
                "summary": "创建存储桶",
                "parameters": [
                    {
                        "description": "bucket name",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BucketPostForm"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.bucketPostJSON"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.bucketPost400JSON"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    }
                }
            }
        },
        "/api/v1/buckets/{id}": {
            "patch": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "#设置存储桶访问权限，提交query参数“public”, true(公有)，false(私有);\n#重命名存储桶，提交query参数“rename”,其值为新名称;\n#可以一次设置多个存储桶访问权限，其余存储桶id通过form ids传递, 重命名时ids无效。\n#同时提交“public”和“rename”参数,忽略“rename”参数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bucket 存储桶"
                ],
                "summary": "设置存储桶访问权限或重命名存储桶",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "bucket id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "设置对象公有或私有, true(公有)，false(私有)",
                        "name": "public",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "重命名桶,值为存储桶新名称",
                        "name": "rename",
                        "in": "query"
                    },
                    {
                        "description": "bucket id list,一次设置多个桶的权限时使用，命重名桶时无效",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.bucketDetailForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.bucketPatchJSON"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    }
                }
            }
        },
        "/api/v1/buckets/{id}/": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取存储桶详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bucket 存储桶"
                ],
                "summary": "获取存储桶详细信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "bucket id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.bucketDetailJSON"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "#可以一次删除多个存储桶，其余存储桶id通过form ids传递。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bucket 存储桶"
                ],
                "summary": "删除存储桶",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "bucket id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "bucket id list",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.bucketDetailForm"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    }
                }
            }
        },
        "/api/v1/dir/{bucketname}/{dirpath}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取目录下目录和对象列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dir 目录"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "bucketname",
                        "name": "bucketname",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "dirpath",
                        "name": "dirpath",
                        "in": "path"
                    },
                    {
                        "type": "integer",
                        "description": "The initial index from which to return the results",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to return per page",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.DirListJSON"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建目录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dir 目录"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "bucketname",
                        "name": "bucketname",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "dirpath",
                        "name": "dirpath",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.DirCreateJSON"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.DirCreate400JSON"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    }
                }
            }
        },
        "/api/v1/jwt-token-refresh/": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "jwt refresh handler",
                "consumes": [
                    "application/json",
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jwt"
                ],
                "parameters": [
                    {
                        "description": "jwt",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/middlewares.JWTRefreshForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    }
                }
            }
        },
        "/api/v1/jwt-token/": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "jwt login handler",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jwt"
                ],
                "parameters": [
                    {
                        "description": "auth info",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/middlewares.JWTLoginForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    }
                }
            }
        },
        "/api/v1/obj/{bucketname}/{objpath}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过文件对象绝对路径,下载文件对象,可通过参数获取文件对象详细信息，或者自定义读取对象数据块",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "object对象"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "bucketname",
                        "name": "bucketname",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "objpath",
                        "name": "objpath",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "The byte offset of object to read",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Byte size to read",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.UserListJSON"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "上传对象分片",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "object对象"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "bucketname",
                        "name": "bucketname",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "objpath",
                        "name": "objpath",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "chunk",
                        "name": "chunk",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "chunk_offset",
                        "name": "chunk_offset",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "chunk_size",
                        "name": "chunk_size",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    }
                }
            }
        },
        "/api/v1/users/": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取用户列表页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user 用户"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "The initial index from which to return the results",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to return per page",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.UserListJSON"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user 用户"
                ],
                "parameters": [
                    {
                        "description": "用户名",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.UserPostForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    }
                }
            }
        },
        "/user/register/": {
            "post": {
                "description": "注册用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Register 注册"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Some ID",
                        "name": "some_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "The initial index from which to return the results",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to return per page",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controllers.BaseJSON"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.BaseJSON": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "code_text": {
                    "type": "string"
                }
            }
        },
        "controllers.BucketListJSON": {
            "type": "object",
            "properties": {
                "buckets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Bucket"
                    }
                },
                "code": {
                    "type": "integer"
                },
                "code_text": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                },
                "next": {
                    "type": "string"
                },
                "page": {
                    "type": "object",
                    "$ref": "#/definitions/controllers.PageNumberInfo"
                },
                "previous": {
                    "type": "string"
                }
            }
        },
        "controllers.BucketPostForm": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "controllers.DirCreate400JSON": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "code_text": {
                    "type": "string"
                },
                "existing": {
                    "type": "boolean"
                }
            }
        },
        "controllers.DirCreateJSON": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "code_text": {
                    "type": "string"
                },
                "dir": {
                    "type": "object",
                    "$ref": "#/definitions/models.HarborObject"
                }
            }
        },
        "controllers.DirListJSON": {
            "type": "object",
            "properties": {
                "bucket_name": {
                    "type": "string"
                },
                "code": {
                    "type": "integer"
                },
                "code_text": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                },
                "dir_path": {
                    "type": "string"
                },
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.HarborObject"
                    }
                },
                "next": {
                    "type": "string"
                },
                "page": {
                    "type": "object",
                    "$ref": "#/definitions/controllers.PageNumberInfo"
                },
                "previous": {
                    "type": "string"
                }
            }
        },
        "controllers.PageNumberInfo": {
            "type": "object",
            "properties": {
                "current": {
                    "type": "integer"
                },
                "final": {
                    "type": "integer"
                }
            }
        },
        "controllers.UserListJSON": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "code_text": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                },
                "next": {
                    "type": "string"
                },
                "privous": {
                    "type": "string"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.UserProfile"
                    }
                }
            }
        },
        "controllers.UserPostForm": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "company": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "controllers.bucketDetailForm": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "controllers.bucketDetailJSON": {
            "type": "object",
            "properties": {
                "bucket": {
                    "type": "object",
                    "$ref": "#/definitions/models.Bucket"
                },
                "code": {
                    "type": "integer"
                },
                "code_text": {
                    "type": "string"
                }
            }
        },
        "controllers.bucketPatchJSON": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "code_text": {
                    "type": "string"
                },
                "public": {
                    "type": "boolean"
                },
                "rename": {
                    "type": "string"
                }
            }
        },
        "controllers.bucketPost400JSON": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "code_text": {
                    "type": "string"
                },
                "data": {
                    "type": "object",
                    "$ref": "#/definitions/controllers.BucketPostForm"
                },
                "existing": {
                    "type": "boolean"
                }
            }
        },
        "controllers.bucketPostJSON": {
            "type": "object",
            "properties": {
                "bucket": {
                    "type": "object",
                    "$ref": "#/definitions/models.Bucket"
                },
                "code": {
                    "type": "integer"
                },
                "code_text": {
                    "type": "string"
                },
                "data": {
                    "type": "object",
                    "$ref": "#/definitions/controllers.BucketPostForm"
                }
            }
        },
        "middlewares.JWTLoginForm": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "middlewares.JWTRefreshForm": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "models.Bucket": {
            "type": "object",
            "properties": {
                "access_permission": {
                    "description": "访问权限",
                    "type": "integer"
                },
                "created_time": {
                    "type": "object",
                    "$ref": "#/definitions/models.TypeJSONTime"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "user_id": {
                    "description": "所属用户id",
                    "type": "integer"
                }
            }
        },
        "models.HarborObject": {
            "type": "object",
            "properties": {
                "dlc": {
                    "description": "该文件的下载次数，目录时dlc为0",
                    "type": "integer"
                },
                "fod": {
                    "description": "True==文件，False==目录",
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "na": {
                    "description": "全路径文件名或目录名",
                    "type": "string"
                },
                "name": {
                    "description": "文件名或目录名",
                    "type": "string"
                },
                "sh": {
                    "description": "为True，则文件可共享，为False，则文件不能共享",
                    "type": "boolean"
                },
                "si": {
                    "description": "文件大小, 字节数",
                    "type": "integer"
                },
                "ult": {
                    "description": "文件的上传时间，或目录的创建时间",
                    "type": "string"
                },
                "upt": {
                    "description": "修改时间",
                    "type": "string"
                }
            }
        },
        "models.TypeJSONTime": {
            "type": "object"
        },
        "models.UserProfile": {
            "type": "object",
            "properties": {
                "company": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{ Schemes: []string{}}

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface {}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
